### PR TITLE
Haskell backend improvements, including Docker support

### PR DESCRIPTION
**Pull request by purcell**

### CODE REVIEW

**Comment by purcell** [comment]
Also added Docker support: have been using this as a test-bed for containerised deployment of Haskell apps to AWS, and figured it could be widely useful.

**Comment by purcell** [comment]
Haskell executable now bundles all the static assets, so it's completely standalone once compiled (though dynamically linked with `libpq` and `libc`). :-)

**Comment by newportandy** [comment]
Running out of work to do so trawling through old PRs @purcell? 😂

**Comment by purcell** [comment]
> Running out of work to do so trawling through old PRs @purcell? 😂

Found this in my list of still-open PRs on github so, yes, tidying up! LOL.

**Comment by purcell** [comment]
Feel like a million years since we were hacking on this...

**Pull request closed without merging**
